//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCG.Template.Resources.Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LCG.Template.Resources.Application.EmailMessages", typeof(EmailMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Already Exists.
        /// </summary>
        public static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Email.
        /// </summary>
        public static string EmailChange {
            get {
                return ResourceManager.GetString("EmailChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Configuration Key Is Empty.
        /// </summary>
        public static string EmailConfigurationKeyFromEmpty {
            get {
                return ResourceManager.GetString("EmailConfigurationKeyFromEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smtp host not configured.
        /// </summary>
        public static string EmailConfigurationKeyHostEmpty {
            get {
                return ResourceManager.GetString("EmailConfigurationKeyHostEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smtp password not configured.
        /// </summary>
        public static string EmailConfigurationKeyPasswordEmpty {
            get {
                return ResourceManager.GetString("EmailConfigurationKeyPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smtp port not configured.
        /// </summary>
        public static string EmailConfigurationKeyPortEmpty {
            get {
                return ResourceManager.GetString("EmailConfigurationKeyPortEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smtp ssl not configured.
        /// </summary>
        public static string EmailConfigurationKeySSLEmpty {
            get {
                return ResourceManager.GetString("EmailConfigurationKeySSLEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New email.
        /// </summary>
        public static string EmailNew {
            get {
                return ResourceManager.GetString("EmailNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old email.
        /// </summary>
        public static string EmailOld {
            get {
                return ResourceManager.GetString("EmailOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email template body.
        /// </summary>
        public static string EmailTemplateBody {
            get {
                return ResourceManager.GetString("EmailTemplateBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sending is disabled in configuration.
        /// </summary>
        public static string EmailTemplateEmailSendingOff {
            get {
                return ResourceManager.GetString("EmailTemplateEmailSendingOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email was sent successfully.
        /// </summary>
        public static string EmailTemplateEmailSendingSuccessfully {
            get {
                return ResourceManager.GetString("EmailTemplateEmailSendingSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recipients.
        /// </summary>
        public static string EmailTemplateEmptyRecipients {
            get {
                return ResourceManager.GetString("EmailTemplateEmptyRecipients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty template.
        /// </summary>
        public static string EmailTemplateEmptyTemplate {
            get {
                return ResourceManager.GetString("EmailTemplateEmptyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substituição ==&gt; EnterpriseName &lt;==.
        /// </summary>
        public static string EmailTemplateEnterpriseNvelocityChange {
            get {
                return ResourceManager.GetString("EmailTemplateEnterpriseNvelocityChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ==&gt; Confirm user link &lt;==.
        /// </summary>
        public static string EmailTemplateFormDisclosure {
            get {
                return ResourceManager.GetString("EmailTemplateFormDisclosure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Template Name.
        /// </summary>
        public static string EmailTemplateName {
            get {
                return ResourceManager.GetString("EmailTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Template Parameters.
        /// </summary>
        public static string EmailTemplateParameters {
            get {
                return ResourceManager.GetString("EmailTemplateParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substituição ==&gt; RetrievePasswordUrl &lt;==.
        /// </summary>
        public static string EmailTemplateRetrievePasswordUrlNvelocityChange {
            get {
                return ResourceManager.GetString("EmailTemplateRetrievePasswordUrlNvelocityChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test email sending.
        /// </summary>
        public static string EmailTemplateSendingEmailSimultaion {
            get {
                return ResourceManager.GetString("EmailTemplateSendingEmailSimultaion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string EmailTemplateSubject {
            get {
                return ResourceManager.GetString("EmailTemplateSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substituição ==&gt; SurveyName &lt;==.
        /// </summary>
        public static string EmailTemplateSurveyNameNvelocityChange {
            get {
                return ResourceManager.GetString("EmailTemplateSurveyNameNvelocityChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substituição ==&gt; SurveyUrl &lt;==.
        /// </summary>
        public static string EmailTemplateSurveyUrlNvelocityChange {
            get {
                return ResourceManager.GetString("EmailTemplateSurveyUrlNvelocityChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Template Title.
        /// </summary>
        public static string EmailTemplateTitle {
            get {
                return ResourceManager.GetString("EmailTemplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string EmailTemplateType {
            get {
                return ResourceManager.GetString("EmailTemplateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ==&gt; UniverseName &lt;==.
        /// </summary>
        public static string EmailTemplateUniverseNameNvelocityChange {
            get {
                return ResourceManager.GetString("EmailTemplateUniverseNameNvelocityChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing.
        /// </summary>
        public static string EmailTemplateViewTitle {
            get {
                return ResourceManager.GetString("EmailTemplateViewTitle", resourceCulture);
            }
        }
    }
}
